import {
  LayoutDashboard,
  Users,
  Boxes,
  EqualSquareIcon,
  HandCoins,
  SquareStack,
  Landmark,
  NotebookText,
  PiggyBank,
  Files,
  ReceiptText,
  BanknoteArrowDown,
  BookMarkedIcon,
  PresentationIcon,
  ShieldUser,
  ShoppingCart,
  Box,
  Settings,
  CalendarDays,
  Wallet,
} from "lucide-react";
export const sideConfig = {
  admin: [
    { name: "Dashboard", path: "/dashboard", icon: LayoutDashboard },
    { name: "Parties", path: "/parties", icon: Users },
    { name: "Items", path: "/items", icon: Boxes },
    { name: "Sales", path: "/sales", icon: Box },
    { name: "Quotation/Estimate", path: "/quotation", icon: EqualSquareIcon },
    { name: "Payment in", path: "/payment", icon: HandCoins },
    { name: "Sales-Return", path: "/salesreturn", icon: SquareStack },
    { name: "Purchases", path: "/purchases", icon: Landmark },
    { name: "Reports", path: "/reports", icon: NotebookText },
    // Account and billing
    { name: "Cash and Bank", path: "/cash", icon: PiggyBank },
    { name: "E-Invoicing", path: "/invoicing", icon: Files },
    { name: "Automated-Bills", path: "/bills", icon: ReceiptText },
    { name: "Expenses", path: "/expenses", icon: BanknoteArrowDown },
    { name: "POS Billing", path: "/pos", icon: BookMarkedIcon },
    // Business Tools
    {
      name: "Attendance & Payroll >",
      path: "/staffattendance",
      icon: PresentationIcon,
      children: [
        {
          name: "Attendance",
          path: "/staffattendance/attendance",
          icon: CalendarDays,
        },
        {
          name: "Payroll",
          path: "/staffattendance/payroll",
          icon: Wallet,
        },
      ],
    },
    { name: "Manage Users", path: "/users", icon: ShieldUser },
    { name: "Online Orders", path: "/online", icon: ShoppingCart },
    { name: "Settings", path: "/settings", icon: Settings },
  ],
  subadmin: [
    { name: "Dashboard", path: "/dashboard", icon: LayoutDashboard },
    { name: "Parties", path: "/parties", icon: Users },
    { name: "Items", path: "/items", icon: Boxes },
    { name: "Sales", path: "/sales", icon: Box },
    { name: "Quotation/Estimate", path: "/quotation", icon: EqualSquareIcon },
    { name: "Payment in", path: "/payment", icon: HandCoins },
    { name: "Sales-Return", path: "/salesreturn", icon: SquareStack },
    { name: "Purchases", path: "/purchases", icon: Landmark },
    { name: "Reports", path: "/reports", icon: NotebookText },
    // Account and billing
    { name: "Cash and Bank", path: "/cash", icon: PiggyBank },
    { name: "E-Invoicing", path: "/invoicing", icon: Files },
    { name: "Automated-Bills", path: "/bills", icon: ReceiptText },
    { name: "Expenses", path: "/expenses", icon: BanknoteArrowDown },
    { name: "POS Billing", path: "/pos", icon: BookMarkedIcon },
    // Business Tools
    {
      name: "Attendance & Payroll >",
      path: "/staffattendance",
      icon: PresentationIcon,
      children: [
        {
          name: "Attendance",
          path: "/staffattendance/attendance",
          icon: CalendarDays,
        },
        {
          name: "Payroll",
          path: "/staffattendance/payroll",
          icon: Wallet,
        },
      ],
    },
    { name: "Manage Users", path: "/users", icon: ShieldUser },
    { name: "Online Orders", path: "/online", icon: ShoppingCart },
    { name: "Settings", path: "/settings", icon: Settings },
  ],
  employee: [
    { name: "Dashboard", path: "/dashboard", icon: LayoutDashboard },
    { name: "Parties", path: "/parties", icon: Users },
    { name: "Items", path: "/items", icon: Boxes },
    { name: "Sales", path: "/sales", icon: Box },
    { name: "Quotation/Estimate", path: "/quotation", icon: EqualSquareIcon },
    { name: "Payment in", path: "/payment", icon: HandCoins },
    { name: "Sales-Return", path: "/salesreturn", icon: SquareStack },
    { name: "Purchases", path: "/purchases", icon: Landmark },
    { name: "Reports", path: "/reports", icon: NotebookText },
    // Account and billing
    { name: "Cash and Bank", path: "/cash", icon: PiggyBank },
    { name: "E-Invoicing", path: "/invoicing", icon: Files },
    { name: "Automated-Bills", path: "/bills", icon: ReceiptText },
    { name: "Expenses", path: "/expenses", icon: BanknoteArrowDown },
    { name: "POS Billing", path: "/pos", icon: BookMarkedIcon },
    // Business Tools
    {
      name: "Attendance & Payroll >",
      path: "/staffattendance",
      icon: PresentationIcon,
      children: [
        {
          name: "Attendance",
          path: "/staffattendance/attendance",
          icon: CalendarDays,
        },
        {
          name: "Payroll",
          path: "/staffattendance/payroll",
          icon: Wallet,
        },
      ],
    },
    { name: "Manage Users", path: "/users", icon: ShieldUser },
    { name: "Online Orders", path: "/online", icon: ShoppingCart },
    { name: "Settings", path: "/settings", icon: Settings },
  ],
};
